apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    discovered_by: kubernetesplugin
  name: httpbin-httpbin-8000
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      app: httpbin
      app.kubernetes.io/instance: httpbin-app
      service: httpbin
  kube:
    selector:
      app: httpbin
    serviceName: httpbin
    serviceNamespace: httpbin
    servicePort: 8000
    serviceSpec:
      rest:
        swaggerInfo:
          url: https://raw.githubusercontent.com/solo-io/solo-blog-edge-argo-15/main/lib/httpbin-openapi.json
